name: Build and Release Signed APK

on:
  push:
    branches:
      - master
  workflow_dispatch: # Allow manual triggering of the workflow

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: gradle

      - name: Get Version Name
        id: version
        run: echo "VERSION_NAME=$(grep VERSION_NAME gradle.properties | cut -d'=' -f2)" >> $GITHUB_ENV

      - name: Decode Keystore
        run: echo "${{ secrets.KEYSTORE_BASE64 }}" | base64 -d -w 0 > keystore.jks

      - name: Grant execute permission for Gradlew
        run: chmod +x ./gradlew

      # Building App
      - name: Build Android APK
        run: ./gradlew assembleRelease 

      # Native APK Signing using apksigner
      - name: Sign APK
        run: |
          # Find apksigner
          APKSIGNER=$(find $ANDROID_SDK_ROOT/build-tools -name apksigner | sort -r | head -n 1)
          echo "Using apksigner at: $APKSIGNER"
          
          # Find unsigned APK
          UNSIGNED_APK=$(find app/build/outputs/apk/release -name "*.apk" | head -n 1)
          if [ -z "$UNSIGNED_APK" ]; then
            echo "Error: Unsigned APK not found!"
            exit 1
          fi
          echo "Found unsigned APK at: $UNSIGNED_APK"
          
          # Sign the APK directly to the workspace output destination
          $APKSIGNER sign --ks keystore.jks \
            --ks-key-alias "${{ secrets.KEY_ALIAS }}" \
            --ks-pass pass:"${{ secrets.KEYSTORE_PASSWORD }}" \
            --key-pass pass:"${{ secrets.KEY_PASSWORD }}" \
            --out "${{ github.workspace }}/Expense Tracker v${{ env.VERSION_NAME }}.apk" \
            $UNSIGNED_APK
          
          echo "APK successfully signed and output to ${{ github.workspace }}/Expense Tracker v${{ env.VERSION_NAME }}.apk"

      - name: Check if APK exists
        run: |
          if [ ! -f "${{ github.workspace }}/Expense Tracker v${{ env.VERSION_NAME }}.apk" ]; then
            echo "APK file not found!"
            exit 1
          fi

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: Expense Tracker Release APK
          path: "${{ github.workspace }}/Expense Tracker v${{ env.VERSION_NAME }}.apk"
          retention-days: 4

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: v${{ env.VERSION_NAME }}
          name: Release v${{ env.VERSION_NAME }}
          draft: false
          prerelease: true
          files: ${{ github.workspace }}/Expense Tracker v${{ env.VERSION_NAME }}.apk
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
