name: Build on Master

on:
  push:
    branches: [ "master" ]
    tags: [ "v*" ]
  pull_request:
    branches: [ "master" ]
    tags: [ "v*" ]

jobs:
  build:
    name: Build App
    runs-on: ubuntu-latest

    steps:
      - name: Clone Repo
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Validate Gradle Wrapper
        uses: gradle/actions/wrapper-validation@v4

      - name: Setup Android SDK
        run: |
          ${ANDROID_SDK_ROOT}/cmdline-tools/latest/bin/sdkmanager "build-tools;34.0.0" # v,34.0.0

      - name: Set up JDK
        uses: actions/setup-java@99b8673ff64fbf99d8d325f52d9a5bdedb8483e9 # v4.2.1
        with:
          java-version: 17
          distribution: adopt

      - name: Set up gradle
        uses: gradle/actions/setup-gradle@65a3beb9413b5a43f94e1eea10a51c507e62b78f # v3.3.0

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Show available actions
        run: ./gradlew tasks

      - name: Build app and run unit tests
        run: ./gradlew assemble
